spring.application.name=all-agency-backend

# ========================================
# CONFIGURATION DU SERVEUR
# ========================================
server.port=${PORT:8080}

# ========================================
# CONFIGURATION R2DBC POSTGRESQL (Réactif)
# ========================================
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:webhook_db}?schema=${DB_SCHEMA:ugate}
spring.r2dbc.username=${DB_USER:postgres}
spring.r2dbc.password=${DB_PASSWORD:root}
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=1
spring.r2dbc.pool.max-size=5
spring.r2dbc.pool.max-acquire-time=30s
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.max-life-time=10m
spring.r2dbc.pool.acquire-retry=3
spring.r2dbc.pool.validation-query=SELECT 1

# ========================================
# ========================================
# LIQUIBASE (Migrations BDD)
# ========================================
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:webhook_db}
spring.liquibase.user=${DB_LIQUIBASE_USERNAME}
spring.liquibase.password=${DB_LIQUIBASE_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.default-schema=${DB_SCHEMA:ugate}
spring.liquibase.liquibase-schema=${DB_SCHEMA:ugate}


# ========================================
# SWAGGER
# ========================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ========================================
# URL DU BACKEND EXTERNE
# ========================================
agency.dashboard.url=${AGENCY_DASHBOARD_URL:http://localhost:8081/api/events}
agency.dashboard.connect-timeout-ms=${AGENCY_DASHBOARD_TIMEOUT:5000}
external.backend.url=${EXTERNAL_BACKEND_URL:http://localhost:8081/api/events}
external.backend.timeout=${EXTERNAL_BACKEND_TIMEOUT:5000}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.export.prometheus.enabled=true

# ========================================
# WEBCLIENT
# ========================================
spring.codec.max-in-memory-size=10MB

# ========================================
# LOGS
# ========================================
logging.level.root=INFO
logging.level.com.agencybooking=DEBUG
logging.level.org.springframework.r2dbc=DEBUG
